
POST http://localhost:4000/api/v1/tracker/products  HTTP/1.1
content-type: application/json

{
      "product": {
      "title": "Queso cremoso La Paulina x kg.",
      "price": 4700,
      "image": {
        "src": "https://carrefourar.vtexassets.com/arquivos/ids/364370-600-auto?v=638264048747430000&width=600&height=auto&aspect=true",
        "alt": "Queso cremoso La Paulina x kg."
      },
      "link": "https://www.carrefour.com.ar/queso-cremoso-la-paulina-x-kg-647989/p",
      "market": "carrefour"
    }
}
###

GET  http://localhost:4000/api/v1/market/search?query=aceite+girasol&market=cordiez
###

content-type: application/json

{
      "product": {
      "title": "Mayonesa Hellmanns Clasica  X237g",
      "price": 132,
      "image": {
        "src": "https://jumboargentina.vtexassets.com/arquivos/ids/687731-500-auto?v=637799529681900000&width=500&height=auto&aspect=true",
        "alt": "Mayonesa Hellmanns Clasica  X237g"
      }

    }
}
###
PUT  http://localhost:4000/api/v1/tracker/products?link=https://www.carrefour.com.ar/queso-cremoso-la-paulina-x-kg-647989/p