
POST http://localhost:4000/api/v1/tracker/products  HTTP/1.1
content-type: application/json

{
      "product": {
      "title": "MARUCHA DE TERNERA ASISTIDA X KG.",
      "price": 6545,
      "image": {
        "src": "https://statics.dinoonline.com.ar/imagenes/full_600x600_ma/3400080_f.jpg",
        "alt": "MARUCHA DE TERNERA ASISTIDA X KG."
      },
      "link": "https://www.dinoonline.com.ar/super/producto/marucha-de-ternera-asistida-x-kg/_/A-3400080-3400080-s",
      "market": "super mami"
    }
}
###

GET  http://localhost:4000/api/v1/market/search?query=aceite+girasol&market=cordiez
###

content-type: application/json

{
      "product": {
      "title": "Mayonesa Hellmanns Clasica  X237g",
      "price": 132,
      "image": {
        "src": "https://jumboargentina.vtexassets.com/arquivos/ids/687731-500-auto?v=637799529681900000&width=500&height=auto&aspect=true",
        "alt": "Mayonesa Hellmanns Clasica  X237g"
      }

    }
}
###
PUT  http://localhost:4000/api/v1/tracker/products?link=https://www.dinoonline.com.ar/super/producto/marucha-de-ternera-asistida-x-kg/_/A-3400080-3400080-s