
POST http://localhost:4000/api/v1/tracker/products  HTTP/1.1
content-type: application/json

{
      "product": {
      "title": "Mayonesa Clasica Hellmanns 475 Gr",
      "price": 965,
      "image": {
        "src": "https://jumboargentina.vtexassets.com/arquivos/ids/806713-800-auto?v=638403358986700000&width=800&height=auto&aspect=true",
        "alt": "Mayonesa Clasica Hellmanns 475 Gr"
      },
      "link": "https://www.jumbo.com.ar/mayonesa-clasica-hellmanns-475-gr/p",
      "market": "jumbo"
    }
}
###

GET  http://localhost:4000/api/v1/market/search?query=aceite+girasol&market=cordiez
###

POST http://localhost:4000/api/v1/tracker/products  HTTP/1.1
content-type: application/json

{
      "product": {
      "title": "Mayonesa Hellmanns Clasica  X237g",
      "price": 132,
      "image": {
        "src": "https://jumboargentina.vtexassets.com/arquivos/ids/687731-500-auto?v=637799529681900000&width=500&height=auto&aspect=true",
        "alt": "Mayonesa Hellmanns Clasica  X237g"
      }

    }
}
###
PUT  http://localhost:4000/api/v1/tracker/products?link=https://www.cotodigital3.com.ar/sitios/cdigi/producto/-chocolate-50-cacao-arcor-fwp-25-grm/_/A-00474736-00474736-200 